// Copyright (c) Yamaha Corporation
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Microsoft Low-Latency Audio driver project.
// Further information: https://aka.ms/asio
// ============================================================================
// ASIO is a registered trademark of Steinberg Media Technologies GmbH.

import "AsioViewModel.idl";


namespace USBAsioControlPanel
{
    [default_interface]
    runtimeclass AsioPage : Microsoft.UI.Xaml.Controls.Page
    {
        AsioPage();

        AsioViewModel ViewModel{ get; };

        Windows.Foundation.IAsyncAction OnDeviceChangedAsyncAsioViewModel();
        Windows.Foundation.IAsyncAction OkButtonClickedAsyncAsioViewModel();

        void DisposeAsioViewModel();

    }
}
